### ISSUE TITLE
Add support for all currencies Paystack has 

### ISSUE THREAD

**Issue by Andrew-Paystack** [tubiz/camptix-paystack#1]
Hey @tubiz , 

I trust you're well. 

I wanted to open a feature request for adding all currencies that Paystack currently supports. At the moment, the plugin supports NGN only. 

Paystack currently supports: `NGN`, `USD`, `GHS`, `ZAR`, and `KES`.

From my perusal of the plugin code, I think I can make similar functions for the [currencies here](https://github.com/tubiz/camptix-paystack/blob/2ea3df10db3fccd6298d6ad377de0a1c2b0f55d5/tbz-camptix-paystack.php#L16).

Is that the recommended way please? I can work on the pull request for this.

**Comment by tubiz** [comment]
@Andrew-Paystack yes that should work. But the plugin will need to be tested with the latest Camptix release and WordPress.

No need to work on the pull request. I will work on this today and have an update release tomorrow with the support for the addtional currencies.

**Comment by Andrew-Paystack** [comment]
Thanks a ton @tubiz!

**Comment by tubiz** [comment]
Closed via #2
